_wandb:
    value:
        cli_version: 0.22.2
        e:
            kc223mdqsfx533ssyh7fuck7aibcgkkg:
                apple:
                    ecpuCores: 4
                    gpuCores: 32
                    memoryGb: 36
                    name: Apple M4 Max
                    pcpuCores: 10
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "2147483648"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "408585195520"
                email: rabaur@ethz.ch
                executable: /Users/raphaelbaur/miniconda3/envs/vae-r-model/bin/python
                git:
                    commit: bcf00020537b8a51dcc3d7efa50af66ac04f8ed9
                host: student-net-ox-dock-1-a-328.intern.ethz.ch
                memory:
                    total: "38654705664"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/raphaelbaur/Documents/var-rew-learning/train.py
                python: CPython 3.11.13
                root: /Users/raphaelbaur/Documents/var-rew-learning
                startedAt: "2025-10-25T14:04:52.569986Z"
                writerId: kc223mdqsfx533ssyh7fuck7aibcgkkg
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.11.13
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
batch_size:
    value: 16
expert_rationality:
    value: 0.4
gamma:
    value: 0.9
grid_size:
    value: 16
kl_restart_epochs:
    value: 10
kl_restart_mult:
    value: 0.5
kl_weight:
    value: 1
lr:
    value: 0.0001
n_dct_basis_fns:
    value: 11
no_wandb:
    value: false
num_demo_samples:
    value: 1024
num_epochs:
    value: 100
num_pref_samples:
    value: 0
num_steps:
    value: 8
p_rand:
    value: 0
pref_rationality:
    value: 1
reward_type:
    value: five_goals
visualize_dataset:
    value: false
wandb_project:
    value: var-rew-learning
wandb_run_name:
    value: null
wandb_tags:
    value: ""
wandb_watch:
    value: false
